image: python:3.8

test:
  stage: test
  script:
  - apt install tk # for HDBSCAN
  - pip install -r requirements.txt
  - sphinx-build -b html -a ./docs/source public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - apt install tk
  - pip install -r requirements.txt
  - sphinx-build -b html -a ./docs/source public
  artifacts:
    paths:
    - public
  only:
  - master
