config:
  email:
    sender: "example@gmail.com"
    receiver: "example@gmail.com"
    password: "password"
  elastic_save:
    username: "debatelab"
    password: "password"
    host: "143.233.226.60"
    port: 9200
    ssh:
      port: 222
      username: "debatelab"
      key_path: "/path/to/key"
  elastic_retrieve:
    username: "elastic"
    password: "password"
    host: "socialwebobservatory.iit.demokritos.gr"
    port: 9200
    ssh:
      port: 222
      username: "debatelab"
      key_path: "/path/to/key"
  adu_data:
    train_csv: "train_adu.csv"
    dev_csv: "dev_adu.csv"
    test_csv: "test_adu.csv"
  rel_data:
    train_csv: "train_rel.csv"
    dev_csv: "dev_rel.csv"
    test_csv: "test_rel.csv"
  stance_data:
    train_csv: "train_stance.csv"
    dev_csv: "dev_stance.csv"
    test_csv: "test_stance.csv"
tasks: ["prep", "train", "eval"]
preprocessing:
  other_label: "O"
  repl_char: "="
  max_len: 512
  pad_token: 0
eval:
  source: "elasticsearch" # options: elasticsearch, file
  model: "best" # options: best, final
adu_model:
  hidden_size: 256
  rnn_layers: 2
  dropout: 0.5
  use_crf: True
  learning_rate: 0.0001
  mini_batch_size: 32
  num_workers: 8
  max_epochs: 150
  patience: 10
  optimizer: Adam
  use_tensorboard: True
  train_with_dev: False
  save_final_model: True
  shuffle: False
rel_model:
  hidden_size: 256
  layers: 2
  use_crf: False
  learning_rate: 0.0001
  mini_batch_size: 32
  num_workers: 8
  max_epochs: 150
  patience: 10
  optimizer: Adam
  use_tensorboard: True
  train_with_dev: False
  save_final_model: True
  shuffle: False